config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :reviews
  resources :products
  get 'products/:id' => 'users#view'
  get 'users/sign_out' => 'products#index'

  root 'products#index'
  resources to: "reviews#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :description, :name, presence: true
  # validates :price_in_cents, numericality: {only_integer: true, greater_than: 0}
  has_many :reviews
  mount_uploader :photo, PhotoUploader
  has_one :user
  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    format("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @review = Review.new
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Teaching Assistant was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Teaching Assistant was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Teaching Assistant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :availability, :photo)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to :back, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:comment, :product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WYNBOOK</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.1.1/normalize.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <header>
    <nav>
      <div id="logo">
        <%= link_to '<WYNBOOK>', products_path %>
      </div>
      <div id="user_nav">
        <% if user_signed_in? %>
        Signed in as <%= current_user.email %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <% else %>
        <%= link_to 'Sign Up', new_user_registration_path %> or <%= link_to 'Sign In', new_user_session_path %>
        <% end %>
      </div>
    </nav>
  </header>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

</body>

<%= yield %>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description, "Skills" %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit "Create Teaching Assistant" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div id= "title">
  <h1>Teaching Assistants</h1>
  <h2>Below are the teaching assistants available for this week.</h2>
</div>

<div id= "post">

  <div id= "postpost">
    <% @products.each do |product| %>
    <div class="poop">
      <div id= "image">
           <%= link_to product_path(product) do %>
           <%= image_tag product.photo.url(:medium) %>
           <% end %>
      <div id= "controls">
          <!-- <p4><%= link_to 'Book', product, class: 'link' %></p4> -->
          <!-- <p5><%= link_to 'Edit', edit_product_path(product), class: 'link'  %></p5>
          <p6><%= link_to 'Remove', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'link' %></p6> -->
      </div>
      </div>
      <div id= description>
          <div id= "name">
            <a1><%= product.name %></a1>
          </div>
          <div id= "skills">
            <a2><%= product.description %></a2>
          </div>
      </div>
   </div>
    <% end %>
  </div>
</div>

<br>




<!-- <add><%= link_to 'Add Teaching Assistant', new_product_path %></add> -->

app/views/products/new.html.erb
<h1>New Teaching Assistant</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->


<div class= "wraper">

  <div class= "profile">
    <%= image_tag @product.photo.url(:medium) %>
    <p>
      <strong>Name:</strong>
      <%= @product.name %>
    </p>
    <p>
      <strong>Skills:</strong>
      <%= @product.description %>
    </p>
    <p>
      <strong>Availability:</strong>
      <%= @product.availability %>
    </p>

    <% if user_signed_in? %>
    <div id= "button">
    <a href="https://calendar.google.com/calendar/render?tab=wc&pli=1#main_7" target="_blank">Book</a>
    </div>
    <% else %>
   <% end %>
  </div>


  <div class= "reviews">
    <h1>Reviews</h1>
        <% @product.reviews.each do |review| %>
        <div class= "divide">
          <p>
            <%= review.comment %>
            <br>
            <br>
            <time>
              Added on: <%= review.created_at.strftime("%d %b. %Y") %>
            </time>
          </p>

        </div>
          <% end %>
          <div id= "formtitle">
            <br>
            <!-- <h3>New Review</h3> -->
            <%= render 'reviews/form' %>
        </div>
  </div>
</div>


<!-- <%= link_to 'Edit', edit_product_path(@product) %> -->
<!-- <%= link_to 'Back', products_path %> -->

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if user_signed_in? %>
  <!-- <%= f.label :comment %> -->
  <!-- <br>
  <br> -->
  <%= f.text_area :comment %>
  </div>
  <% if @product.nil? %>
  <div class="field">
  <%= f.label :product_id %><br>
  <%= f.text_field :product_id %>
  </div>
  <% else %>
  <%= f.hidden_field :product_id, value: @product.id %>
  <% end %>


  <div class="actions">

  <%= f.submit %>
<% else %>
<% end %>

</div>

  <% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.comment %></td>
        <td><%= review.product.name %></td>
        <!-- <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product.name %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<% if @review.product.nil? %>
  <%= link_to 'Back', reviews_path %>
<% else %>
  <%= link_to 'Back', @review.product %>
<% end %>